type Mutation {
  createCollection(input: CreateCollectionInput!): Collection!
  updateCollection(id: ID!, input: UpdateCollectionInput!): Collection!
  removeCollection(ids: [ID!]!): Boolean!
}

type Query {
  collections(input: CollectionListInput): CollectionList!
}

input CreateCollectionInput {
  name: String!
  description: String
  enabled: Boolean
  contentType: CollectionContentType!
  products: [ID!]
  assets: [AssetInCollectionInput!]
  subCollections: [ID!]
}

input UpdateCollectionInput {
  name: String
  description: String
  enabled: Boolean
  products: [ID!]
  assets: [AssetInCollectionInput!]
  subCollections: [ID!]
}

input AssetInCollectionInput {
  id: ID!
}

extend input CollectionFilters {
  enabled: BooleanFilter
  contentType: CollectionContentType
}
