type Query {
  favorites(input: ProductListInput): VariantList!
}

type Mutation {
  addToFavorites(input: AddToFavoritesInput!): FavoriteResult!
  removeFromFavorites(ids: [ID!]!): Boolean!
}

input AddToFavoritesInput {
  variantId: ID!
}

type FavoriteResult {
  variant: Variant
  apiErrors: [FavoriteErrorResult!]!
}

type FavoriteErrorResult {
  code: FavoriteErrorCode!
  message: String!
}

enum FavoriteErrorCode {
  ALREADY_IN_FAVORITES
}
