type OrderLine implements Node {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
  unitPrice: Int!
  quantity: Int!

  lineSubtotal: Int!
  lineTotal: Int!

  """
  Array of all order-line-level discounts applied to the line
  Populated every time order line is modified.
  Use this field to show data of current discounts applied to the order line
  """
  discounts: [ActiveDiscount!]!

  productVariant: Variant!
}

type OrderLineList implements List {
  items: [OrderLine!]!
  count: Int!
  pageInfo: PageInfo!
}
