type Shipment implements Node {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
  trackingCode: String
  carrier: String
  amount: Int!
  total: Int!
  method: String!

  """
  Array of all shipment-level discounts applied to the shipment
  Populated every time order shipment is modified.
  Use this field to show data of current discounts applied to the shipment
  """
  discounts: [ActiveDiscount!]!

  order: Order!
}
